<?php /* -*- mode: c; -*- */

  error_reporting(E_ALL);

  $col_border  = "#404040";
  $col_content = "#D0D0D0";
  $col_leech   = "#808080";
  $col_menu    = "#A0A0A0";
  $col_marker  = "#E04040";
  $col_bg      = "#707070";
  $col_bg2     = "#808080";
  $col_bliss   = $col_menu;
  $col_text    = $col_border;

  if ($argv[1] == "marker")
    exit ($col_border." ".$col_marker);

  if ($argv[1] == "border")
    exit ($col_border);

  if ($argv[1] == "bg")
    exit ($col_bg." ".$col_bg2);

  $debug = 0;
  $base = substr($argv[1], 0, strrpos($argv[1], "."));

  $menu = $base;
  if ($base == "index")
    $menu = "home";

  $x_max = 17;
  $y_max = 7;

  $layers = array();
  $files = array();

  for ($i = 2; $i < $argc; $i++)
  {
    $name = $argv[$i];

    $files[] = $name;

    if ($name == "index")
      $name = "home";

    $layers[] = $name;
  }  

  function render_link ($filename)
  {
    echo "<a href=\"".$filename."\">".basename($filename)."</a> ("
        .round (filesize ("../".$filename) / 1024)." kb)";
  }

  function render_linkmsg ($filename, $msg)
  {
    echo "<a href=\"".$filename."\">".$msg."</a> ("
        .round (filesize ("../".$filename) / 1024)." kb)";
  }

  function render_picture ($filename, $msg)
  {
    echo "<p class=\"screenshot\">\n"
        ."  <a href=\"pictures/".$filename."\">\n"
        ."  <img class=\"screenshot\" "
        ."src=\"pictures/thumb/small_".$filename."\" "
        ."alt=\"(picture)\" />\n"
        ."  </a><br />\n".$msg
        ." (".round (filesize ("../pictures/".$filename) / 1024)
        ." kb)\n</p>";
  }
/*
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
          "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
*/
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
  <head>
    <link rel="icon" href="favicon.png" type="image/png" />

<?php echo "<title>bliss::".$base."</title>\n"; ?>
<?php
  if ($debug)
    echo "<meta http-equiv=\"refresh\" "
        ."CONTENT=\"2; URL=index.html\" />\n";
?>
    <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />

<!-- ==================================
     ====> DO NOT EDIT THIS FILE! <====
     ==================================
     (bel warp voor de .php broncode :) -->
      
    <style type="text/css">
      body { 
        font-family: verdana, arial, sans-serif;
        font-size: 8pt;
        letter-spacing: 0.1em; 
        line-height: 1.1em;
        text-decoration: none;
        text-align: justify; 
        background-image: url(bg);
<?php echo "background-color: ".$col_bg.";\ncolor: ".$col_text.";\n"; ?>

        margin: 0; padding: 0; border: 0; 
      }
      <!-- should be 5px or 6px, but galeon (mozilla) is buggy. -->
      tr.bliss { margin: 0; padding: 0; border: 0; line-height: 1px; }
      td.bliss { margin: 0; padding: 0; border: 0; line-height: 1px; }
      img.bliss { margin: 0; padding: 0; border: 0; line-height: 1px; }
      img { border: 0; }
      td.links { 
        margin: 0; 
        padding-left: 0; 
        padding-right: 0; 
        padding-bottom: 0;
        padding-top: 1em;
        border-left: 0; 
        border-right: 0; 
        border-top: 0;
<?php echo "border-bottom: 1px dashed ".$col_border.";\n"; ?>

        font-family: verdana, arial, sans-serif;
        font-size: 8pt;
        letter-spacing: 0.1em; 
        line-height: 0.9em;
      }
      p { text-align: justify; padding-left: 2em; padding-right: 2em; }
      div.links { padding-left: 2em; padding-right: 2em; width: 600px; }
      p.menu { 
        text-align: right; 
        font-size: 10pt; 
        line-height: 1.2em;

        padding-left: 0.5em; 
        padding-right: 0.5em; 
        padding-top: 0;
        padding-bottom: 0;

        margin: 0;
        border: 0;
      }
      div.content {
        position: absolute;
        top: 32px;
        left: 188px;
        width: 600px;

        font-family: verdana, arial, sans-serif;
        font-size: 8pt;
        letter-spacing: 0.1em; 
        line-height: 1.1em;
        text-decoration: none;
        text-align: justify; 

        padding: 0;
        margin-top: 0;
        margin-left: 0;
        margin-bottom: 1em;
<?php echo "background: ".$col_content.";\n"; ?>
<?php echo "border: 2px solid ".$col_border.";\n"; ?>
      }
      p.leechbar {
        margin-left: 1em;
        margin-right: 1em;
<?php echo "background: ".$col_leech.";\n"; ?>
<?php echo "border: 2px solid ".$col_border.";\n"; ?>
      }
      img.screenshot { clear: both; 
<?php echo "border: 1px solid ".$col_border.";\n"; ?>
      }
      p.valid { text-align: right; }
      p.sig { text-align: right; font-style: italic; }
      p.screenshot { clear: both; font-style: italic; }
      h2 { 
        text-align: center; 
        font-size: 10pt; 
        margin-left: 1em;
        margin-right: 1em;
<?php echo "background: ".$col_leech.";\n"; ?>
<?php echo "border: 2px solid ".$col_border.";\n"; ?>
      }

      a:visited { color: <?php echo $col_text; ?>; text-decoration: none; text-align: right; font-weight: bolder; }
      a:link    { color: <?php echo $col_text; ?>; text-decoration: none; text-align: right; font-weight: bolder; }
      a:active  { color: <?php echo $col_text; ?>; text-decoration: none; text-align: right; font-weight: bolder; }
    </style>

<?php
/*
    not used, so leave it out for now.
   
    <!-- width and height detection -->
    <script type="text/javascript">
    <!--
      var width;
      var height;

      if ((document.body) && (document.body.clientWidth))
        width = document.body.clientWidth;
      else if (window.innerWidth)
        width = window.innerWidth;
      else
        width = 600; // assume a safe value

      if ((document.body) && document.body.clientHeight) 
        height = document.body.clientHeight;
      else if (window.innerHeight)
        height = window.innerHeight;
      else
        height = 300; // assume a safe value.
    -->
    </script>

    <!-- ugh. browsers suck. -->
    <script type="text/javascript">
    <!--
    function layer (name)
    {
      if (document.getElementById)
        return document.getElementById(name).style;
      else if (document.all)
        return document.all[name].style;
      else 
        return null;
    }
    -->
    </script>
*/
?>

    <!-- msg effect, idea from web4096 compo (round #2)
    ===================================================
    4 - go find the message / meri (m@m13.sk) (IE + NS)
    ===================================================
    http://web4096.message.sk -->
    <script type="text/javascript">
    <!--
      var x_max = <?php echo $x_max; ?>;
      var y_max = <?php echo $y_max; ?>;
      var msg_x;
      var msg_y;
      var msg_direction;
      var x;
      var y;
      var int1;
      var int1_busy = 0;
      var msg_speed = 2;
      var msg_pause = 4000;

      var msg = new Array ( 2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2, 
                            2, 00,  2,  2,  2, 00,  2, 00,  2, 00, 00, 00,  2, 00, 00, 00,  2, 
                            2, 00,  2,  2,  2, 00,  2,  2,  2, 00,  2,  2,  2, 00,  2,  2,  2, 
                            2, 00, 00, 00,  2, 00,  2, 00,  2, 00, 00, 00,  2, 00, 00, 00,  2, 
                            2, 00,  2, 00,  2, 00,  2, 00,  2,  2,  2, 00,  2,  2,  2, 00,  2, 
                            2, 00, 00, 00,  2, 00,  2, 00,  2, 00, 00, 00,  2, 00, 00, 00,  2, 
                            2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2);

      var onoff = new Array (16*6);

      function rnd_box() { return Math.round (Math.random () * 1); }
      function rnd_x() { return Math.round (Math.random () * (x_max-1)); }
      function rnd_y() { return Math.round (Math.random () * (y_max-1)); }
  
      function img(name)
      {
        if (document.layers)
          return document.layers['bliss'].document.images[name];
        else
          return document.images[name];
      }

      function msg_invert()
      {
        for (y=0; y<y_max; y++)
          for (x=0; x<x_max; x++)
            msg[y*x_max+x] = msg[y*x_max+x] ? 0 : 2;
      }

      function main()
      {
        img('box_0_0').src = 0;
        img('box_1_0').src = 0;

        int0 = setInterval("box_init()", (msg_pause / 2));
      }

      function box_init()
      {
        clearInterval (int0);
        int0 = 0;
<?php
//        for (y=0; y<y_max; y++)
//          for (x=0; x<x_max; x++)
//            img('box_' + x + '_' + y).src = 0;
?>
        for (y=0; y<y_max; y++)
          for (x=0; x<x_max; x++)
            onoff[y*x_max+x] = 1;

        if (rnd_box ())
          msg_invert();

        msg_x = 0;
        msg_y = 0;

        int1 = setInterval("box_do()", 80);
      }

      function box_do()
      {
        x = rnd_x();
        y = rnd_y();
        if (onoff[y*x_max+x])
          img('box_' + x + '_' + y).src = rnd_box();
      }

      function msg_init()
      {
        if (!int1_busy)
        {
          int1_busy = 1;
          int1 = setInterval("msg_on()", msg_speed);
          msg_x = 0;
          msg_y = 0;
          msg_direction = 1;
        }
      }                                                                                      

      function msg_on()
      {
        onoff[msg_y*x_max+msg_x] = 0;
        img('box_' + msg_x + '_' + msg_y).src = msg[msg_y*x_max+msg_x];

        msg_x += msg_direction;
        if ((msg_x == x_max) || (msg_x == -1))
        {
          if (msg_x == -1)    { msg_direction =  1; msg_x+=1; }
          if (msg_x == x_max) { msg_direction = -1; msg_x-=1; }
          msg_y++;
          if (msg_y == y_max)
          {
            clearInterval(int1);
            int1 = setInterval("msg_wait()", msg_pause);
            msg_x = 0;
            msg_y = 0;
          }
        }
      }

      function msg_wait()
      {
        clearInterval(int1);
        int1 = setInterval("msg_off()", msg_speed);
      }
                                                                                      
      function msg_off()
      {
        onoff[msg_y*x_max+msg_x] = 1;
        img('box_' + msg_x + '_' + msg_y).src = msg[msg_y*x_max+msg_x] ? 1 : 0;

        msg_y++;
        if (msg_y == y_max)
        {
          msg_y = 0;
          msg_x++;
          if (msg_x == x_max)
          {
            clearInterval(int1);
            int1_busy = 0;
          }
        }
      }
    -->                                                                              
    </script>

  </head>
  <body onload="main();">

    <div id="bliss"
<?php echo "  style=\"position: absolute; top: 32px; left: 32px; width: 140px; "
      ."background: ".$col_bliss."; border: 2px solid ".$col_border.";\">\n"; ?>
      <table cellpadding="0" cellspacing="1" border="0" onclick="msg_init()">
<?php

   $src = 2;
   for ($y = 0; $y < $y_max; $y++)
   {
     echo "<tr class=\"bliss\">\n";
     for ($x = 0; $x < $x_max; $x++)
     {
       echo "  <td class=\"bliss\"><img class=\"bliss\" "
           ."id=\"box_".$x."_".$y."\" src=\"".$src."\" "
           ."width=\"7\" height=\"5\" alt=\" \" /></td>\n";
       if ($src) $src--;
     }
     echo "</tr>";
   }
?>
      </table>
    </div>

<?php
  $pos = 98;

  reset ($layers);
  while (list ($key, $name) = each ($layers)) 
  {
    $href = $files[$key].".html";

    if ($menu == $name)
      echo "<div id=\"".$name."_marker\" class=\"".$name."_marker\"\n"
          ."  style=\"position: absolute; top: ".$pos."px; left: 32px; width: 24px; "
          ."background: ".$col_marker."; border: 2px solid ".$col_border.";\">\n"
          ."<p class=\"menu\">&nbsp;</p>\n</div>";

    echo "<div id=\"".$name."_menu\" class=\"".$name."_menu\"\n"
        ."  style=\"position: absolute; top: ".$pos."px; left: 64px; width: 108px; "
        ."background: ".$col_menu."; border: 2px solid ".$col_border.";\">\n"
        ."<p class=\"menu\"><a href=\"".$href."\">".$name."</a></p>\n</div>\n";

    $pos += 32;
  }
?>

<?php

  echo "<div id=\"".$base."_content\" class=\"content\">\n"
      ."  <small>&nbsp;</small>\n";

  include($base.".in");

  echo "  <small>&nbsp;</small>\n</div>\n";
?>

<?php
      /* agh. looks nice in konqueror and galeon.
         doesn't work on opera 5, and fucks up IE5.

    <script type="text/javascript">
    <!--
      if (layer('bliss'))
        {
          echo "layer('bliss').position = 'fixed';\n";

          reset ($layers);
          while (list ($key, $name) = each ($layers)) 
          {
            echo "layer('".$name."_marker').position = 'fixed';\n";
            echo "layer('".$name."_menu').position = 'fixed';\n";
          }  
        }
    -->
    </script>
        */
?>

  </body>
</html>
